[crawl_options]
log_file = './crawl.log'
database_location = './crawl.db'

[profiles]
[profiles.my_website]
    locations = [
        'https://spider2.vercel.app'
    ]

    depth = 2
    method = 'hash'  # cosine
    same_domain = true  # Todo: regex match

