[crawl_options]
log_file = './crawl.log'
database_location = './databases'
debug = false
profile = true
cache_dir = './data'
graph_dir = './graphs'

[profiles]
#  [profiles.my_website]
#     locations = [
#         'https://sp1d3r.vercel.app'
#     ]

#     depth = 3
#     same_domain = true
#     filter = []

[profiles.scrape_me]
    locations = [
        'https://scrapeme.live/shop/'
    ]
    depth = 3
    same_domain = true
    filter = [
        '^http://scrapeme.live/page/.*',
        '^https://scrapeme.live/shop/.*/?add-to-cart=.*',
        '.*\.png$'
    ]

    match = [
        '^http://scrapeme.live/shop/.*'
    ]