[crawl_options]
log_file = './crawl.log'
database_location = './databases'
debug = false
profile = true
cache_dir = './data'
graph_dir = './graphs'
index = "./indexes.pkl"
workers = 8

[profiles]
 [profiles.my_website]
    locations = [
        'https://sp1d3r.vercel.app'
    ]

    depth = 3
    same_domain = true
    filter = []

    match = [
        '^https://sp1d3r.vercel.app/.*'
    ]

[profiles.scrape_me]
    locations = [
        'https://scrapeme.live/shop/'
    ]

    depth = 3
    
    filter = [
        '^https://scrapeme.live/page/.*',
        '^http://scrapeme.live/page/.*',
        '^https://scrapeme.live/shop/.*/?add-to-cart=.*',
        '.*\.png$',
        '.*\.jpg$',
        '^https://scrapeme.live/product-tag/.*',
        '^https://scrapeme.live/product-category/.*',
        '^https://scrapeme.live/wp-login.php.*$'
    ]

    match = [
        '^https://scrapeme.live/*'
    ]
