[crawl_options]
log_file = './crawl.log'
database_location = './databases'
debug = false
profile = true
cache_dir = './data'
graph_dir = './graphs'
index = "./indexes.pkl"
workers = 8

[profiles]
 [profiles.my_website]
    locations = [
        'https://sp1d3r.vercel.app'
    ]

    depth = 3
    same_domain = true
    filter = []

    match = [
        '^https://sp1d3r.vercel.app/.*'
    ]

#     match = [
#         '^https://sp1d3r.vercel.app/.*$'
#     ]

[profiles.scrape_me]
    locations = [
        'https://github.com/spider2048/'
    ]

    depth = 3
    
    filter = [
        # 'https://github.com/spider2048/.*\?.*$'
    ]

    match = [
        '^https://github.com/spider2048/.*$'
    ]
